### PR TITLE
fix(visible-inline-block) change class to inline-block under visible-…

### PR DESCRIPTION
**Pull request by SuEric**
…inline-block.styl

### CODE REVIEW

**Comment by SuEric** [comment]
Hey @lgg hope can merge this ASAP; thanks.

**Comment by SuEric** [comment]
Hey @lgg . Can you accept this one please?

**Comment by lgg** [comment]
@SuEric sorry, i didn't have opportunity to merge this. I will accept this soon.

**Comment by lgg** [comment]
@SuEric Thank you very much for your patch! :heart:

**Pull request merged**
